name = "MoonScenty Presents Minecraft 1.21.1"
author = "MoonScenty"
version = "0.2.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cad2a54789470c2fd9d33f3dbe0f7778bce577655d5c625af8bf395d562b9f09"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
