name = "MoonScenty Presents Minecraft 1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4548112ce5edc4584940bbcc3116114311e9d38ec6bc0e9a5feb12beeb110726"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
