#Disable all vanilla Minecraft advancements
disableVanillaAdvancements = true
#Disable advancements added by other mods
disableModdedAdvancements = false
#Hide the advancements screen (L key)
hideAdvancementScreen = true
